apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: seccomp-profiles-installer
resources:
- serviceaccount.yaml
- seccomp-profiles-pv.yaml
- seccomp-profiles-pvc.yaml
- daemonset.yaml
- seccomp-profiles
- rbac
