apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: seccomp-profiles-installer
  name: seccomp-profile-installer-anyuid
  namespace: lars-sandbox
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: seccomp-profile-installer
  namespace: lars-sandbox
